# Generated by Django 3.0.2 on 2020-01-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_hobbies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='given_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rating_givenby', to='user_hobbies.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='user_hobbies.User'),
        ),
    ]
