# Generated by Django 3.0.2 on 2020-01-22 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_hobbies', '0003_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
