# Generated by Django 3.0.2 on 2020-01-22 09:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_hobbies', '0004_auto_20200122_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='hardwork',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='honesty',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
