# Generated by Django 3.0.2 on 2020-01-23 14:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_hobbies', '0009_departments_userdepartment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserDepartment',
            new_name='UserDepartments',
        ),
    ]
