# Generated by Django 3.0.2 on 2020-01-27 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_hobbies', '0010_auto_20200123_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhobby',
            name='hobby',
        ),
        migrations.AddField(
            model_name='userhobby',
            name='hobby',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='User_Hobby', to='user_hobbies.Hobbies'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userhobby',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
