# Generated by Django 3.0.2 on 2020-01-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_hobbies', '0011_auto_20200127_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userhobby',
            name='hobby',
        ),
        migrations.AddField(
            model_name='userhobby',
            name='hobby',
            field=models.ManyToManyField(to='user_hobbies.Hobbies'),
        ),
    ]
